"""add tipo_cuerpo to sesiones_tratamiento

Revision ID: 1ed9060c2089
Revises: d9e8f0b23456
Create Date: 2026-02-01 13:09:12.787540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed9060c2089'
down_revision: Union[str, Sequence[str], None] = 'd9e8f0b23456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sesiones_tratamiento', sa.Column('tipo_cuerpo', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sesiones_tratamiento', 'tipo_cuerpo')
    # ### end Alembic commands ###
