"""add_auth_columns

Revision ID: 21a83bb0db2e
Revises: 358c0277e66f
Create Date: 2026-01-23 18:56:03.020989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a83bb0db2e'
down_revision: Union[str, Sequence[str], None] = '358c0277e66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed accidental drops for treatments/sessions
    op.add_column('usuarios', sa.Column('auth_id', sa.String(length=100), nullable=True))
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'usuarios', ['auth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('usuarios', 'auth_id')
    # Removed accidental creates for treatments/sessions in downgrade
    # ### end Alembic commands ###
