"""add_hora_column

Revision ID: b55f479d7ccc
Revises: b5935d261cdd
Create Date: 2026-01-24 11:23:51.701114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55f479d7ccc'
down_revision: Union[str, Sequence[str], None] = 'b5935d261cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citas', sa.Column('hora', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citas', 'hora')
    # ### end Alembic commands ###
