"""Add treatments module

Revision ID: b5935d261cdd
Revises: 21a83bb0db2e
Create Date: 2026-01-23 20:52:39.334621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5935d261cdd'
down_revision: Union[str, Sequence[str], None] = '21a83bb0db2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sesiones_tratamiento', sa.Column('estado', sa.String(length=20), nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('abdomen_alto_cm', sa.Integer(), nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('cintura_cm', sa.Integer(), nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('abdomen_bajo_cm', sa.Integer(), nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('cadera_cm', sa.Integer(), nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('peso_kg', sa.Integer(), nullable=True))
    op.alter_column('sesiones_tratamiento', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sesiones_tratamiento_id_tratamiento'), table_name='sesiones_tratamiento')
    op.drop_constraint(op.f('sesiones_tratamiento_id_tratamiento_fkey'), 'sesiones_tratamiento', type_='foreignkey')
    op.drop_constraint(op.f('sesiones_tratamiento_id_empleado_fkey'), 'sesiones_tratamiento', type_='foreignkey')
    op.create_foreign_key(None, 'sesiones_tratamiento', 'tratamientos', ['id_tratamiento'], ['id_tratamiento'])
    op.drop_column('sesiones_tratamiento', 'foto_url')
    op.drop_column('sesiones_tratamiento', 'duracion_minutos')
    op.drop_column('sesiones_tratamiento', 'fecha_actualizacion')
    op.drop_column('sesiones_tratamiento', 'id_empleado')
    op.drop_column('sesiones_tratamiento', 'productos_utilizados')
    op.add_column('tratamientos', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.alter_column('tratamientos', 'sesiones_planificadas',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tratamientos', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tratamientos_id_empleado_creador_fkey'), 'tratamientos', type_='foreignkey')
    op.create_foreign_key(None, 'tratamientos', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.drop_column('tratamientos', 'fecha_actualizacion')
    op.drop_column('tratamientos', 'id_empleado_creador')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamientos', sa.Column('id_empleado_creador', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tratamientos', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tratamientos', type_='foreignkey')
    op.create_foreign_key(op.f('tratamientos_id_empleado_creador_fkey'), 'tratamientos', 'usuarios', ['id_empleado_creador'], ['id_usuario'])
    op.alter_column('tratamientos', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tratamientos', 'sesiones_planificadas',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('tratamientos', 'id_usuario')
    op.add_column('sesiones_tratamiento', sa.Column('productos_utilizados', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('id_empleado', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('duracion_minutos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiones_tratamiento', sa.Column('foto_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sesiones_tratamiento', type_='foreignkey')
    op.create_foreign_key(op.f('sesiones_tratamiento_id_empleado_fkey'), 'sesiones_tratamiento', 'usuarios', ['id_empleado'], ['id_usuario'])
    op.create_foreign_key(op.f('sesiones_tratamiento_id_tratamiento_fkey'), 'sesiones_tratamiento', 'tratamientos', ['id_tratamiento'], ['id_tratamiento'], ondelete='CASCADE')
    op.create_index(op.f('ix_sesiones_tratamiento_id_tratamiento'), 'sesiones_tratamiento', ['id_tratamiento'], unique=False)
    op.alter_column('sesiones_tratamiento', 'fecha_registro',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('sesiones_tratamiento', 'peso_kg')
    op.drop_column('sesiones_tratamiento', 'cadera_cm')
    op.drop_column('sesiones_tratamiento', 'abdomen_bajo_cm')
    op.drop_column('sesiones_tratamiento', 'cintura_cm')
    op.drop_column('sesiones_tratamiento', 'abdomen_alto_cm')
    op.drop_column('sesiones_tratamiento', 'estado')
    # ### end Alembic commands ###
